package exceptionhandling;

public class ExceptionHandlingExapmple {

	public static void main(String[] args) {
		
			try {
				int c=4/2;
				System.out.println("output is " + c);
				
			} catch (ArithmeticException e1) {
				
				System.out.println("Exception handled");
			}
			
			
	
		

	}

}
